export enum Icon {
    Arrow = "img/arrow.svg",
    ArrowMenu = "img/arrow-menu.svg",
    Miracle = "img/icon-left.svg",
    Article = "img/article.svg",
    Audio = "img/audio.svg",
    Box = "img/box.svg",
    Canvas = "img/canvas.svg",
    Dots = "img/dots.svg",
    Hand = "img/hand.svg",
    Iframe = "img/iframe.svg",
    Img = "img/img.svg",
    SDouble = "img/S-double.svg",
    TDouble = "img/T-double.svg",
    TUnderline = "img/T-underline.svg",
    T = "img/T.svg",
    Video = "img/video.svg",
}
